# Site settings
title: Jesus D. Gonzalez L., Ph.D.
email: youremailaddress@gmail.com
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: https://scholar.google.com/citations?hl=es&user=pBC8EsoAAAAJ&view_op=list_works&sortby=pubdate
instagram_url:
linkedin_url: https://www.linkedin.com/in/jesus-gonzalez-llorente/
pinterest_url:
slack_url:
twitter_url:
orcid_url: https://orcid.org/0000-0001-6525-7657

# Build settings
markdown: GFM
